export {default as All} from './All'
export {default as Games} from './Games'
export {default as HeadToHeadDetails} from './HeadToHeadDetails'
export {default as Home} from './Home'
export {default as Loader} from './Loader'
export {default as Login} from './Login'
export {default as NavBar} from './NavBar'
export {default as PlayerIcon} from './PlayerIcon'